name: jason_company
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  activout_firebase_options_selector: ^1.0.0
  advanced_search: ^2.2.3
  awesome_notifications: ^0.9.3+1
  cloud_firestore: ^4.12.1
  collection: ^1.18.0
  connectivity_plus: ^5.0.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.2.1
  dart_ping: ^7.0.2
  dotenv: ^4.2.0
  dropdown_button2: ^2.3.9
  excel: ^4.0.2
  expandable: ^5.0.1
  file_picker: ^8.0.3
  firebase_analytics: ^10.10.0
  firebase_auth: ^4.19.5
  firebase_auth_platform_interface: ^7.2.6
  firebase_core: ^2.24.2
  firebase_database: ^10.3.2
  firebase_messaging: ^14.8.0
  firebase_storage: ^11.4.0
  firedart: ^0.9.8
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.0
  gap: ^3.0.1
  http: ^1.2.1
  intl: ^0.19.0
  material_table_view: ^4.0.2
  network_discovery: ^1.0.0
  observe_internet_connectivity: ^1.0.2
  open_file: ^3.3.2
  path_provider: ^2.1.1
  pdf: ^3.10.6
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  printing: ^5.11.1
  provider: ^6.0.5
  section_view: ^2.0.6
  shared_preferences: ^2.2.3
  sticky_headers: ^0.3.0+2
  syncfusion_flutter_core: null
  syncfusion_flutter_datagrid: null
  syncfusion_flutter_datagrid_export: ^25.2.4
  syncfusion_flutter_pdf: ^25.2.4
  syncfusion_flutter_signaturepad: ^25.2.4
  syncfusion_flutter_xlsio: ^25.2.4
  time_picker_spinner_pop_up: ^2.0.0
  two_dimensional_scrollables: ^0.2.1
  web_socket_channel: ^3.0.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: null
  flutter_test:
    sdk: flutter
  objectbox_generator: ^2.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
