// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:jason_company/models/moderls.dart';
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2015244925239452168),
      name: 'ChipBlockModel',
      lastPropertyId: const IdUid(13, 3261639009652717753),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1790817178631293790),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3811530322767209551),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6671159875649631399),
            name: 'color',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8814152568559353469),
            name: 'density',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3733810281531421738),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3174536976192947366),
            name: 'serial',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5798955569406690223),
            name: 'number',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 96514242531701386),
            name: 'width',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 5727796209942622936),
            name: 'lenth',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 3035959731439974874),
            name: 'scissor',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 7899842113936739697),
            name: 'hight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 3574241914799094215),
            name: 'wight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 3261639009652717753),
            name: 'notes',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 97117940785492925),
      name: 'ChipFraction',
      lastPropertyId: const IdUid(4, 9223158076297314543),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8376135679287693917),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4846088898683996665),
            name: 'width',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4803332614112622551),
            name: 'lenth',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 9223158076297314543),
            name: 'hight',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 501138952087645226),
      name: 'ChipfinalProducut',
      lastPropertyId: const IdUid(12, 1850975540094892586),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5942773127681590999),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1496649440216294200),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6673775500635340521),
            name: 'color',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8419808130356394852),
            name: 'density',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2922816607494254128),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1692453529083943286),
            name: 'amount',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1440803366176324108),
            name: 'number',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7959595773506429201),
            name: 'width',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 5366723079530702261),
            name: 'lenth',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 2144281151360239731),
            name: 'hight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 4774758903985168373),
            name: 'company',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 1850975540094892586),
            name: 'scissor',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(3, 501138952087645226),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ChipBlockModel: EntityDefinition<ChipBlockModel>(
        model: _entities[0],
        toOneRelations: (ChipBlockModel object) => [],
        toManyRelations: (ChipBlockModel object) => {},
        getId: (ChipBlockModel object) => object.id,
        setId: (ChipBlockModel object, int id) {
          object.id = id;
        },
        objectToFB: (ChipBlockModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final colorOffset = fbb.writeString(object.color);
          final typeOffset = fbb.writeString(object.type);
          final serialOffset = fbb.writeString(object.serial);
          final notesOffset = fbb.writeString(object.notes);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, colorOffset);
          fbb.addFloat64(3, object.density);
          fbb.addOffset(4, typeOffset);
          fbb.addOffset(5, serialOffset);
          fbb.addFloat64(6, object.number);
          fbb.addFloat64(7, object.width);
          fbb.addFloat64(8, object.lenth);
          fbb.addFloat64(9, object.scissor);
          fbb.addFloat64(10, object.hight);
          fbb.addFloat64(11, object.wight);
          fbb.addOffset(12, notesOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final colorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final densityParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final serialParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final numberParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final widthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final lenthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final scissorParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final hightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final wightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final notesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 28, '');
          final object = ChipBlockModel(
              id: idParam,
              title: titleParam,
              color: colorParam,
              density: densityParam,
              type: typeParam,
              serial: serialParam,
              number: numberParam,
              width: widthParam,
              lenth: lenthParam,
              scissor: scissorParam,
              hight: hightParam,
              wight: wightParam,
              notes: notesParam);

          return object;
        }),
    ChipFraction: EntityDefinition<ChipFraction>(
        model: _entities[1],
        toOneRelations: (ChipFraction object) => [],
        toManyRelations: (ChipFraction object) => {},
        getId: (ChipFraction object) => object.id,
        setId: (ChipFraction object, int id) {
          object.id = id;
        },
        objectToFB: (ChipFraction object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.width);
          fbb.addFloat64(2, object.lenth);
          fbb.addFloat64(3, object.hight);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final widthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final lenthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final hightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = ChipFraction(
              id: idParam,
              width: widthParam,
              lenth: lenthParam,
              hight: hightParam);

          return object;
        }),
    ChipfinalProducut: EntityDefinition<ChipfinalProducut>(
        model: _entities[2],
        toOneRelations: (ChipfinalProducut object) => [],
        toManyRelations: (ChipfinalProducut object) => {},
        getId: (ChipfinalProducut object) => object.id,
        setId: (ChipfinalProducut object, int id) {
          object.id = id;
        },
        objectToFB: (ChipfinalProducut object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final colorOffset = fbb.writeString(object.color);
          final typeOffset = fbb.writeString(object.type);
          final companyOffset = fbb.writeString(object.company);
          final scissorOffset = fbb.writeString(object.scissor);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, colorOffset);
          fbb.addFloat64(3, object.density);
          fbb.addOffset(4, typeOffset);
          fbb.addFloat64(5, object.amount);
          fbb.addFloat64(6, object.number);
          fbb.addFloat64(7, object.width);
          fbb.addFloat64(8, object.lenth);
          fbb.addFloat64(9, object.hight);
          fbb.addOffset(10, companyOffset);
          fbb.addOffset(11, scissorOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final scissorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final colorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final densityParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final numberParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final widthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final lenthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final hightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final companyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final object = ChipfinalProducut(
              id: idParam,
              title: titleParam,
              scissor: scissorParam,
              color: colorParam,
              density: densityParam,
              type: typeParam,
              amount: amountParam,
              number: numberParam,
              width: widthParam,
              lenth: lenthParam,
              hight: hightParam,
              company: companyParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ChipBlockModel] entity fields to define ObjectBox queries.
class ChipBlockModel_ {
  /// see [ChipBlockModel.id]
  static final id =
      QueryIntegerProperty<ChipBlockModel>(_entities[0].properties[0]);

  /// see [ChipBlockModel.title]
  static final title =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[1]);

  /// see [ChipBlockModel.color]
  static final color =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[2]);

  /// see [ChipBlockModel.density]
  static final density =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[3]);

  /// see [ChipBlockModel.type]
  static final type =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[4]);

  /// see [ChipBlockModel.serial]
  static final serial =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[5]);

  /// see [ChipBlockModel.number]
  static final number =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[6]);

  /// see [ChipBlockModel.width]
  static final width =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[7]);

  /// see [ChipBlockModel.lenth]
  static final lenth =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[8]);

  /// see [ChipBlockModel.scissor]
  static final scissor =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[9]);

  /// see [ChipBlockModel.hight]
  static final hight =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[10]);

  /// see [ChipBlockModel.wight]
  static final wight =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[11]);

  /// see [ChipBlockModel.notes]
  static final notes =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[12]);
}

/// [ChipFraction] entity fields to define ObjectBox queries.
class ChipFraction_ {
  /// see [ChipFraction.id]
  static final id =
      QueryIntegerProperty<ChipFraction>(_entities[1].properties[0]);

  /// see [ChipFraction.width]
  static final width =
      QueryDoubleProperty<ChipFraction>(_entities[1].properties[1]);

  /// see [ChipFraction.lenth]
  static final lenth =
      QueryDoubleProperty<ChipFraction>(_entities[1].properties[2]);

  /// see [ChipFraction.hight]
  static final hight =
      QueryDoubleProperty<ChipFraction>(_entities[1].properties[3]);
}

/// [ChipfinalProducut] entity fields to define ObjectBox queries.
class ChipfinalProducut_ {
  /// see [ChipfinalProducut.id]
  static final id =
      QueryIntegerProperty<ChipfinalProducut>(_entities[2].properties[0]);

  /// see [ChipfinalProducut.title]
  static final title =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[1]);

  /// see [ChipfinalProducut.color]
  static final color =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[2]);

  /// see [ChipfinalProducut.density]
  static final density =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[3]);

  /// see [ChipfinalProducut.type]
  static final type =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[4]);

  /// see [ChipfinalProducut.amount]
  static final amount =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[5]);

  /// see [ChipfinalProducut.number]
  static final number =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[6]);

  /// see [ChipfinalProducut.width]
  static final width =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[7]);

  /// see [ChipfinalProducut.lenth]
  static final lenth =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[8]);

  /// see [ChipfinalProducut.hight]
  static final hight =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[9]);

  /// see [ChipfinalProducut.company]
  static final company =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[10]);

  /// see [ChipfinalProducut.scissor]
  static final scissor =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[11]);
}
