// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../models/moderls.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8270035808394733948),
      name: 'ChipBlockModel',
      lastPropertyId: const IdUid(14, 6627704771325751214),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3631079449638806069),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8501412458957975813),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 9215423942782512455),
            name: 'color',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 111570357293258598),
            name: 'density',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2196007138835517895),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4100383895590901476),
            name: 'serial',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2429974254413219178),
            name: 'number',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8833240990742853681),
            name: 'width',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 744817791137649596),
            name: 'lenth',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 3225118537304772849),
            name: 'scissor',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 6951603700313459266),
            name: 'hight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 827258658796565619),
            name: 'wight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 3028011085251127184),
            name: 'notes',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 6627704771325751214),
            name: 'description',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 5558201871620107121),
      name: 'ChipFraction',
      lastPropertyId: const IdUid(4, 2841735505030618490),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6566109302821088290),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3613850702257291216),
            name: 'width',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3075867272590908109),
            name: 'lenth',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2841735505030618490),
            name: 'hight',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 4677854116925811042),
      name: 'ChipfinalProducut',
      lastPropertyId: const IdUid(12, 4103394296519612335),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5910189028422840968),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5946957732526766171),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 445662547417877837),
            name: 'color',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4798961399589036996),
            name: 'density',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7175544107474135524),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1697998348812150836),
            name: 'amount',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6395949023927143793),
            name: 'number',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7630725252404375574),
            name: 'width',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 2700800057006974690),
            name: 'lenth',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 6388336104792188983),
            name: 'hight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 5395221979200628178),
            name: 'company',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 4103394296519612335),
            name: 'scissor',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(3, 4677854116925811042),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ChipBlockModel: EntityDefinition<ChipBlockModel>(
        model: _entities[0],
        toOneRelations: (ChipBlockModel object) => [],
        toManyRelations: (ChipBlockModel object) => {},
        getId: (ChipBlockModel object) => object.id,
        setId: (ChipBlockModel object, int id) {
          object.id = id;
        },
        objectToFB: (ChipBlockModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final colorOffset = fbb.writeString(object.color);
          final typeOffset = fbb.writeString(object.type);
          final serialOffset = fbb.writeString(object.serial);
          final notesOffset = fbb.writeString(object.notes);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(15);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, colorOffset);
          fbb.addFloat64(3, object.density);
          fbb.addOffset(4, typeOffset);
          fbb.addOffset(5, serialOffset);
          fbb.addFloat64(6, object.number);
          fbb.addFloat64(7, object.width);
          fbb.addFloat64(8, object.lenth);
          fbb.addFloat64(9, object.scissor);
          fbb.addFloat64(10, object.hight);
          fbb.addFloat64(11, object.wight);
          fbb.addOffset(12, notesOffset);
          fbb.addOffset(13, descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final colorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final densityParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final serialParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final numberParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final widthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final lenthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final scissorParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final hightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final wightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final notesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 28, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 30, '');
          final object = ChipBlockModel(
              id: idParam,
              title: titleParam,
              color: colorParam,
              density: densityParam,
              type: typeParam,
              serial: serialParam,
              number: numberParam,
              width: widthParam,
              lenth: lenthParam,
              scissor: scissorParam,
              hight: hightParam,
              wight: wightParam,
              notes: notesParam,
              description: descriptionParam);

          return object;
        }),
    ChipFraction: EntityDefinition<ChipFraction>(
        model: _entities[1],
        toOneRelations: (ChipFraction object) => [],
        toManyRelations: (ChipFraction object) => {},
        getId: (ChipFraction object) => object.id,
        setId: (ChipFraction object, int id) {
          object.id = id;
        },
        objectToFB: (ChipFraction object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.width);
          fbb.addFloat64(2, object.lenth);
          fbb.addFloat64(3, object.hight);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final widthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final lenthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final hightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = ChipFraction(
              id: idParam,
              width: widthParam,
              lenth: lenthParam,
              hight: hightParam);

          return object;
        }),
    ChipfinalProducut: EntityDefinition<ChipfinalProducut>(
        model: _entities[2],
        toOneRelations: (ChipfinalProducut object) => [],
        toManyRelations: (ChipfinalProducut object) => {},
        getId: (ChipfinalProducut object) => object.id,
        setId: (ChipfinalProducut object, int id) {
          object.id = id;
        },
        objectToFB: (ChipfinalProducut object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final colorOffset = fbb.writeString(object.color);
          final typeOffset = fbb.writeString(object.type);
          final companyOffset = fbb.writeString(object.company);
          final scissorOffset = fbb.writeString(object.scissor);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, colorOffset);
          fbb.addFloat64(3, object.density);
          fbb.addOffset(4, typeOffset);
          fbb.addFloat64(5, object.amount);
          fbb.addFloat64(6, object.number);
          fbb.addFloat64(7, object.width);
          fbb.addFloat64(8, object.lenth);
          fbb.addFloat64(9, object.hight);
          fbb.addOffset(10, companyOffset);
          fbb.addOffset(11, scissorOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final scissorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final colorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final densityParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final numberParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final widthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final lenthParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final hightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final companyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final object = ChipfinalProducut(
              id: idParam,
              title: titleParam,
              scissor: scissorParam,
              color: colorParam,
              density: densityParam,
              type: typeParam,
              amount: amountParam,
              number: numberParam,
              width: widthParam,
              lenth: lenthParam,
              hight: hightParam,
              company: companyParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ChipBlockModel] entity fields to define ObjectBox queries.
class ChipBlockModel_ {
  /// see [ChipBlockModel.id]
  static final id =
      QueryIntegerProperty<ChipBlockModel>(_entities[0].properties[0]);

  /// see [ChipBlockModel.title]
  static final title =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[1]);

  /// see [ChipBlockModel.color]
  static final color =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[2]);

  /// see [ChipBlockModel.density]
  static final density =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[3]);

  /// see [ChipBlockModel.type]
  static final type =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[4]);

  /// see [ChipBlockModel.serial]
  static final serial =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[5]);

  /// see [ChipBlockModel.number]
  static final number =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[6]);

  /// see [ChipBlockModel.width]
  static final width =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[7]);

  /// see [ChipBlockModel.lenth]
  static final lenth =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[8]);

  /// see [ChipBlockModel.scissor]
  static final scissor =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[9]);

  /// see [ChipBlockModel.hight]
  static final hight =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[10]);

  /// see [ChipBlockModel.wight]
  static final wight =
      QueryDoubleProperty<ChipBlockModel>(_entities[0].properties[11]);

  /// see [ChipBlockModel.notes]
  static final notes =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[12]);

  /// see [ChipBlockModel.description]
  static final description =
      QueryStringProperty<ChipBlockModel>(_entities[0].properties[13]);
}

/// [ChipFraction] entity fields to define ObjectBox queries.
class ChipFraction_ {
  /// see [ChipFraction.id]
  static final id =
      QueryIntegerProperty<ChipFraction>(_entities[1].properties[0]);

  /// see [ChipFraction.width]
  static final width =
      QueryDoubleProperty<ChipFraction>(_entities[1].properties[1]);

  /// see [ChipFraction.lenth]
  static final lenth =
      QueryDoubleProperty<ChipFraction>(_entities[1].properties[2]);

  /// see [ChipFraction.hight]
  static final hight =
      QueryDoubleProperty<ChipFraction>(_entities[1].properties[3]);
}

/// [ChipfinalProducut] entity fields to define ObjectBox queries.
class ChipfinalProducut_ {
  /// see [ChipfinalProducut.id]
  static final id =
      QueryIntegerProperty<ChipfinalProducut>(_entities[2].properties[0]);

  /// see [ChipfinalProducut.title]
  static final title =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[1]);

  /// see [ChipfinalProducut.color]
  static final color =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[2]);

  /// see [ChipfinalProducut.density]
  static final density =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[3]);

  /// see [ChipfinalProducut.type]
  static final type =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[4]);

  /// see [ChipfinalProducut.amount]
  static final amount =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[5]);

  /// see [ChipfinalProducut.number]
  static final number =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[6]);

  /// see [ChipfinalProducut.width]
  static final width =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[7]);

  /// see [ChipfinalProducut.lenth]
  static final lenth =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[8]);

  /// see [ChipfinalProducut.hight]
  static final hight =
      QueryDoubleProperty<ChipfinalProducut>(_entities[2].properties[9]);

  /// see [ChipfinalProducut.company]
  static final company =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[10]);

  /// see [ChipfinalProducut.scissor]
  static final scissor =
      QueryStringProperty<ChipfinalProducut>(_entities[2].properties[11]);
}
